version: '3.4'
services:
  specialize-type-demo-share:
    image: alfresco-share-specialize-type-demo:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../specialize-type-demo-share-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: specialize-type-demo-acs
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"
      - "${share.debug.port}:8888"
  specialize-type-demo-acs:
    image: alfresco-content-services-specialize-type-demo:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../specialize-type-demo-platform-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - specialize-type-demo-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - specialize-type-demo-postgres
  specialize-type-demo-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - specialize-type-demo-db-volume:/var/lib/postgresql/data
  specialize-type-demo-ass:
    image: alfresco/alfresco-search-services:1.4.3.2
    environment:      
      #Solr needs to know how to register itself with Alfresco
      - SOLR_ALFRESCO_HOST=specialize-type-demo-acs
      - SOLR_ALFRESCO_PORT=8080
      #Alfresco needs to know how to call solr
      - SOLR_SOLR_HOST=specialize-type-demo-ass
      - SOLR_SOLR_PORT=8983
      #Create the default alfresco and archive cores
      - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
      #HTTP by default
      - ALFRESCO_SECURE_COMMS=none
    ports:
      - "8983:8983"
    volumes:
      - specialize-type-demo-ass-volume:/opt/alfresco-search-services/contentstore
      - specialize-type-demo-ass-volume:/opt/alfresco-search-services/data
      
volumes:
  specialize-type-demo-acs-volume:
    external: true
  specialize-type-demo-db-volume:
    external: true
  specialize-type-demo-ass-volume:
    external: true